on:
  push:
    branches: [ master ]
    paths:
    - 'terraform/dev/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
    - 'terraform/dev/**'

jobs:
  terraform_dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        components: [vpc, iam, s3]
      max-parallel: 1
    defaults:
      run:
        shell: bash
        working-directory: terraform/dev/${{ matrix.components }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: technote-space/get-diff-action@v1
      with:
        PREFIX_FILTER: |
          terraform/dev/${{ matrix.components }}/
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      if: env.GIT_DIFF
    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
      if: env.GIT_DIFF
    - name: Terraform Init
      run: terraform init
      if: env.GIT_DIFF
    - name: Terraform Format
      run: terraform fmt -check
      if: env.GIT_DIFF
    - name: Terraform Plan
      run: terraform plan
      if: env.GIT_DIFF
    - name: Terraform Apply
      if: env.GIT_DIFF && github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
